export const ERROR = {
	PAGE_NOT_EXIT: 'PAGE NOT EXIT',
	ACCESS_DENIED: 'ACCESS DENIED',
	CATEGORY_NOT_FOUND: 'CATEGORY NOT FOUND',
	CATEGORIES_NOT_FOUND: 'CATEGORIES NOT FOUND',
	CATEGORIES_MISSING: 'missing categories...',
	PRODUCT_NOT_FOUND: 'PRODUCT NOT FOUND',
	PRODUCTS_NOT_FOUND: 'PRODUCTS NOT FOUND',
	CART_NOT_FOUND: 'CART NOT FOUND',
	ORDER_NOT_FOUND: 'ORDER NOT FOUND',
	FORM_NOT_VALID: 'FORM NOT VALID',
};
