export const PATH = {
	HOME: '/',
	CATALOG: '/catalog',
	USERS: '/users',
	ORDERS: '/orders',
	ORDER: '/order',
	CARTS: '/carts',
	PRODUCT: '/product',
	PRODUCTS: '/products',
	CATEGORIES: '/categories',
	COMMENTS: '/comments',
	ROLES: '/roles',
	REGISTER: '/register',
	LOGIN: '/login',
	LOGOUT: '/logout',
	ADMIN: '/admin',
	OFFICE: 'http://surl.li/vyjneo',
};
