export const ACTIONS = {
	COMMENT_REMOVE: 'COMMENT_REMOVE',
	COMMENTS_SET: 'COMMENTS_SET',
	COMMENT_ADD: 'COMMENT_ADD',

	USER_SET: 'SET_USER',
	USER_REMOVE: 'USER_REMOVE',

	CATEGORIES_SET: 'CATEGORIES_SET',
	CATEGORY_ADD: 'CATEGORY_ADD',
	CATEGORY_UPDATE: 'CATEGORY_UPDATE',
	CATEGORY_REMOVE: 'CATEGORY_REMOVE',

	PRODUCTS_SET: 'PRODUCTS_SET',
	PRODUCTS_ADD: 'PRODUCTS_ADD',
	PRODUCTS_UPDATE: 'PRODUCTS_UPDATE',
	PRODUCTS_REMOVE: 'PRODUCTS_REMOVE',

	PRODUCT_SET: 'PRODUCT_SET',
	PRODUCT_CLEAR: 'PRODUCT_CLEAR',
	PRODUCT_ADD: 'PRODUCT_ADD',
	PRODUCT_REMOVE: 'PRODUCT_REMOVE',
	PRODUCT_UPDATE: 'PRODUCT_UPDATE',

	CART: 'CART',
	OPEN_CART: 'OPEN_CART',
	CLOSE_CART: 'CLOSE_CART',
	CART_ADD: 'CART_ADD',
	CART_REMOVE: 'CART_REMOVE',
	CART_RESET: 'CART_RESET',
	CLEAR_CART: 'CART_CLEAR',


	OPEN_ORDERS: 'OPEN_ORDERS',
	CLOSE_ORDERS: 'CLOSE_ORDERS',
	ORDERS_SET: 'ORDER_SET',
	ORDER_ADD: 'ORDER_ADD',
	ORDER_REMOVE: 'ORDER_REMOVE',
	ORDERS_CLEAR: 'ORDERS_CLEAR',

	OPEN_LOGIN: 'OPEN_LOGIN',
	CLOSE_LOGIN: 'CLOSE_LOGIN',
	OPEN_REGISTER: 'OPEN_REGISTER',
	CLOSE_REGISTER: 'CLOSE_REGISTER',

	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',

	LOGOUT: 'LOGOUT',
	LOGIN: 'LOGIN',
	REGISTER: 'REGISTER',
};


